name: release-downloader
description: Download releases from GitHub releases
author: kaleidawave
branding:
  icon: arrow-up-circle
  color: red

inputs:
  items:
    description: A comma separated list of items to download
    required: true

runs:
  using: "composite"
  steps:
  - id: run-linux
    shell: bash
    if: ${{ runner.os == 'Linux' }}
    run: |
      curl -L 'https://github.com/kaleidawave/release-downloader/releases/download/assets/release-downloader' > out
      chmod +x ./out
      ./out '${{ inputs.items }}'

  - id: run-windows
    shell: bash
    if: ${{ runner.os == 'Windows' }}
    run: |
      curl -L 'https://github.com/kaleidawave/release-downloader/releases/download/assets/release-downloader.exe' > out.exe
      ./out.exe '${{ inputs.items }}'

  - id: set-path
    shell: bash
    run: echo "$HOME/.local/bin" > "$GITHUB_PATH"
