[package]
name = "release-downloader"
description = "Downloads releases from GitHub"
authors = ["Ben <kaleidawave@gmail.com>"]
version = "0.0.2"
edition = "2024"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["release", "github"]
repository = "https://github.com/kaleidawave/experiments"

[lib]
name = "release_downloader"
path = "lib.rs"

[[bin]]
name = "release-downloader"
path = "main.rs"

[features]
default = ["decompress"]
self-update = ["dep:self-replace"]
decompress = ["dep:flate2", "dep:tar", "dep:zip"]

[dependencies]
# Decompression utilities
flate2 = { version = "1.1.2", optional = true }
tar = { version = "0.4.44", optional = true }

# For downloading and extracing API results
mashrl = "0.0.4"
simple-json-parser = "0.0.5"

# For the library
self-replace = { version = "1.5", optional = true }

[target.'cfg(windows)'.dependencies]
zip = { version = "5", optional = true, default-features = false, features = [
	"bzip2",
	"deflate",
	"lzma",
	"zstd",
] }

# [patch.crates-io]
# mashrl = { path = "../../../experiments/simple-http-requester/mashrl" }

[package.metadata.commands]
test = "cargo run -- 'kaleidawave/experiments@assets[spectra]' private/bin"
