name: Build and publish libraries and assets

on:
  push:
    paths:
      - '**.rs'

jobs:
  publish-libraries:
    permissions: write-all

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: kaleidawave/release-downloader@main
        with:
          items: kaleidawave/crates-release-gh-action@assets[crates-release]

      - id: auth
        uses: rust-lang/crates-io-auth-action@v1

      - id: release
        name: Crates publish
        uses: kaleidawave/crates-release-gh-action@improvements
        with:
          # $ {{ github.event.inputs.version }}
          version: patch
          crates-token: ${{ steps.auth.outputs.token }}

      - name: Push updated Cargo.toml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Release: ${{ steps.release.outputs.new-version }}"
          git push origin ${{ steps.checkout.outputs.ref }}

      - name: Notify discord
        uses: dusmartijngames/discord-webhook-notify@master
        with:
          severity: info
          text: "Released version ${{ steps.release.outputs.new-versions-description }}"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_ENDPOINT }}

  publish-assets:
    needs: publish-libraries

    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        - os: windows-latest
          platform-name: x86_64-pc-windows
          executable-extension: ".exe"
        - os: ubuntu-latest
          platform-name: x86_64-unknown-linux

    runs-on: ${{ matrix.os }}

    env:
      PROFILE: dev
      OUT: target/debug
      GH_RELEASE: assets

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Set variables
        shell: bash
        id: information
        run: |
          echo "GITHUB_RUN_DATE=$(TZ="Europe/London" date +"%Y-%m-%d %T")" >> "$GITHUB_OUTPUT"
          echo "GIT_LAST_COMMIT=$(git log -n 1 --format="%H")" >> "$GITHUB_OUTPUT"

      - name: Build binary
        working-directory: release-downloader
        run: cargo build --profile ${{ env.PROFILE }}
        env:
          GITHUB_RUN_DATE: ${{ steps.information.outputs.GITHUB_RUN_DATE }}
          GIT_LAST_COMMIT: ${{ steps.information.outputs.GIT_LAST_COMMIT }}

      - name: Publish binary
        shell: bash
        working-directory: release-downloader
        run: |
          FROM="./${{ env.OUT }}/release-downloader${{ matrix.executable-extension }}"
          TO="release-downloader-${{ matrix.platform-name }}${{ matrix.executable-extension }}"
          gh release upload $GH_RELEASE "$FROM#$TO" --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}