name: Build and publish libraries and assets

on:
  push

jobs:
  publish-libraries:
    if: false

    permissions: write-all

    strategy:
      matrix:
        library: [release-downloader]

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - id: checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: kaleidawave/release-downloader@main
        with:
          items: kaleidawave/crates-release-gh-action@assets[crates-release]

      - name: Update version
        id: update-version
        run: crates-release change-version patch
        working-directory: ${{ matrix.library }}

      # - uses: rust-lang/crates-io-auth-action@v1
      #   id: auth

      - run: cargo publish --allow-dirty
        working-directory: ${{ matrix.library }}
        # env:
          # CARGO_REGISTRY_TOKEN: $ { { secrets.CARGO_REGISTRY_TOKEN }}
          # CARGO_REGISTRY_TOKEN: $ { { steps.auth.outputs.token }}

      - name: Push updated Cargo.toml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -u .
          git commit -m "Release: ${{ steps.update-version.outputs.mashrl }}"
          git push origin ${{ steps.checkout.outputs.ref }}

  publish-assets:
    # needs: publish-libraries

    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        binary: [release-downloader]
        include:
        - os: windows-latest
          platform-name: x86_64-pc-windows
          executable-extension: ".exe"
        - os: ubuntu-latest
          platform-name: x86_64-unknown-linux

    runs-on: ${{ matrix.os }}

    env:
      LEVEL: debug
      GH_RELEASE: assets

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Set variables
        id: information
        run: |
          echo "GITHUB_RUN_DATE=$(TZ="Europe/London" date +"%Y-%m-%d %T")" >> "$GITHUB_OUTPUT"
          echo "GIT_LAST_COMMIT=$(git log -n 1 --format="%H")" >> "$GITHUB_OUTPUT"
          IFS='~' read -r binary example <<< '${{ matrix.binary }}'
          echo "WORKING_DIRECTORY=$binary" >> "$GITHUB_OUTPUT"
          if [ -n "$example" ]; then
            echo "BUILD_SPECIFIER=--example $example" >> "$GITHUB_OUTPUT"
            echo "ASSET_PATH=examples/$example" >> "$GITHUB_OUTPUT"
          else
            echo "BUILD_SPECIFIER=" >> "$GITHUB_OUTPUT"
            echo "ASSET_PATH=$binary" >> "$GITHUB_OUTPUT"
          fi

        shell: bash

      - name: Build binary
        working-directory: ${{ steps.information.outputs.WORKING_DIRECTORY }}
        run: cargo build ${{ steps.information.outputs.BUILD_SPECIFIER }}
        env:
          GITHUB_RUN_DATE: ${{ steps.information.outputs.GITHUB_RUN_DATE }}
          GIT_LAST_COMMIT: ${{ steps.information.outputs.GIT_LAST_COMMIT }}

      - name: Publish binary
        working-directory: ${{ steps.information.outputs.WORKING_DIRECTORY }}
        run: |
          FROM="./target/$LEVEL/${{ steps.information.outputs.ASSET_PATH }}${{ matrix.executable-extension }}"
          TO="${{ matrix.binary }}-${{ matrix.platform-name }}${{ matrix.executable-extension }}"
          gh release upload $GH_RELEASE "$FROM#$TO" --clobber
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}